version: "3.5"

services:
  api01: &api
    # Lembre-se de que seu serviço HTTP deve estar hospedado num repositório
    # publicamente acessível! Ex.: hub.docker.com
    build:
      context: .
      dockerfile: DockerfileApi.dev
    hostname: api01
    platform: linux/arm64
    environment:
      - DB_HOSTNAME=db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rinha
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_THREADS_VIRTUAL_ENABLED=true
      - SPRING_THREADS_VIRTUAL_ENABLED_MANUALLY=false
      - SPRING_RESOURCES_CHAIN_ENABLED=true
      - JAVA_OPTS=-Xms108m -Xmx128m
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=123asd

    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    # Não é necessário expor qualquer porta além da porta do load balancer,
    # mas é comum as pessoas o fazerem para testarem suas APIs e conectarem
    # ao banco de dados na fase de desenvolvimento.
    ports:
      - "8081:8080"
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "205MB"

  api02:
    # Essa sintaxe reusa o que foi declarado em 'api01'.
    <<: *api
    hostname: api02
    platform: linux/arm64
    environment:
      - DB_HOSTNAME=db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rinha
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_THREADS_VIRTUAL_ENABLED=true
      - SPRING_THREADS_VIRTUAL_ENABLED_MANUALLY=false
      - SPRING_RESOURCES_CHAIN_ENABLED=true
      - JAVA_OPTS=-Xms108m -Xmx128m
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=123asd

    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    platform: linux/arm64
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999"
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "50MB"


  redis:
      image: redis:7-alpine
      platform: linux/arm64
      hostname: redis
      command: [ "redis-server", "--requirepass", "123asd" ]
      ports:
        - "6379:6379"
      ulimits:
        nofile:
          soft: 1000000
          hard: 1000000
      deploy:
        resources:
          limits:
            cpus: "0.3"
            memory: "50MB"


networks:
  backend:
    driver: bridge
  payment-processor:
    external: true